name: aot_error_reproduction
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.2

dependencies:
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  lints: ^2.0.0
  test: ^1.21.0
